<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJMLU88v\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJMLU88v/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJMLU88v.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJMLU88v\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJMLU88v\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JMLU88v',
    'container.build_id' => '203e5a0b',
    'container.build_time' => 1643580802,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJMLU88v');
